### ISSUE TITLE
Retrieving security hotspot information

### ISSUE THREAD

**Issue by puffycow** [shijl0925/python-sonarqube-api#19]
I want to pull just security hotspot information from my projects so I try this:

`sonar.issues.search_issues(componentKeys=keys[3], types='SECURITY_HOTSPOT')`

And the error thrown is:

`sonarqube.utils.exceptions.ValidationError: Error in request. Possibly validation error [400]: Value of parameter 'types' (SECURITY_HOTSPOT) must be one of: [CODE_SMELL, BUG, VULNERABILITY]`

I am using version Community 8.6.1. I see the web api has a specific hotspots API but I don't see it's use in this library.

**Comment by shijl0925** [comment]
I have add the hotspots web api in v1.2.1. please update the package.

**Comment by puffycow** [comment]
Confirmed, thanks!
