### ISSUE TITLE
(Question) Unable to increase timeout

### ISSUE THREAD

**Issue by MinionAttack** [shijl0925/python-sonarqube-api#22]
Hi, I am trying to increase the default timeout value and I am not able to do it.

Reading the docs I can see:

[Timeout in RestClient](https://python-sonarqube-api.readthedocs.io/en/1.2.1/_modules/sonarqube/utils/rest_client.html?highlight=timeout)

But when coding I'm not sure where I should change the value, as when I check the debugging I don't see any effect.

Regards.

**Comment by shijl0925** [comment]
I fix it in version 1.2.2. You can try it now.

**Comment by MinionAttack** [comment]
Thank you!
