### ISSUE TITLE
[consult]Which Sonar version is the project based on?

### ISSUE THREAD

**Issue by ontheway01** [shijl0925/python-sonarqube-api#3]
I have two inquiries。
Firstly,which verison is the based?
Then,Is there an update release for Sonar 7.9 in the future?
Waiting for your response.

**Comment by shijl0925** [comment]
the code is based on V7.9. and I will keep updating this code

**Comment by shijl0925** [comment]
这个项目最新的代码已经支持几乎所有的api。欢迎fork，欢迎提issue。
The latest code of this project already supports almost all APIs. Welcome to fork, welcome to raise issue.
