### ISSUE TITLE
No feature for listing Pull request Overview and file level issue

### ISSUE THREAD

**Issue by dhananjayagupta** [shijl0925/python-sonarqube-api#37]
![image](https://user-images.githubusercontent.com/88882117/138070789-2b2d791d-4b2e-45a4-a70b-3b192a7d0e92.png)

**Comment by shijl0925** [comment]
https://github.com/shijl0925/python-sonarqube-api/blob/master/docs/examples/project_pull_requests.rst#examples

List the pull requests of a project.:
```
project_pull_requests = sonar.project_pull_requests.search_project_pull_requests(project="my_project")
```
