### ISSUE TITLE
ps parameter in issue/hotspots search doesn't work

### ISSUE THREAD

**Issue by shemi-plgs** [shijl0925/python-sonarqube-api#38]
I want to get the number of issues/hotspots in a certain project. I only want the total number of these issues, however when i do a search i get the JSON with all the issues f.e :

 `
sonar.hotspots.search_hotspots(projectKey=component)
`

When i do **len** on this result i get the total number, but i've requested the whole JSON (which is really heavy).

----

If i do a **curl** request i can actually filter with the **ps** parameter to get a lightweight JSON :

`
curl -sX GET -u <TOKEN>:  "http://<SONAR_URL>:9000/api/hotspots/search?projectKey=<PROJECTKEY>&ps=1"
`

This also returns the total number of hotspots in the result which is good since it is what i'm aiming for.

But when i try to use the same parameter in the python api i get the same result with or without the ps parameter.

Is this a normal API behavior, also is their any other way to get only the total number of issues / hotspots ? 

===========
sonarqube is 9.1
python-sonarqube-api is 1.2.4

**Comment by shijl0925** [comment]
update v1.2.7

example code:

```
from sonarqube import SonarQubeClient

if __name__ == "__main__":
    sonarqube_url = 'http://localhost:9000'
    username = "admin"
    password = "admin"

    sonarhandler = SonarQubeClient(sonarqube_url=sonarqube_url, username=username, password=password)

    endpoint = "/api/hotspots/search"
    params = {
        "projectKey": "xxx",
        "ps": 1
    }
    result = sonarhandler.request_get(endpoint, params=params)
    total = result.get("paging").get("total")
    print(total)
```
