### ISSUE TITLE
JSON Decoding Error

### ISSUE THREAD

**Issue by firas-jolha** [shijl0925/python-sonarqube-api#42]
Hello,

When I try to list the items of generators which are return values of functions such as `sonar.users.search_users` or `sonar.projects.search_projects()`, I am getting the following error. I updated the `simplejson` package to 3.17.6 and still getting the same error.

`simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by shijl0925** [comment]
please show you code.
