### ISSUE TITLE
1.2.4 or 1.2.5?

### ISSUE THREAD

**Issue by rantoniuk** [shijl0925/python-sonarqube-api#43]
[This](https://pypi.org/project/python-sonarqube-api/) shows version 1.2.5 but [GH shows latest 1.2.4](https://github.com/shijl0925/python-sonarqube-api/releases). 
What was released/changed in 1.2.5?

**Comment by shijl0925** [comment]
I push 1.2.5 tag and release, you can see detail changed in the commit history.
