### ISSUE TITLE
Organisation filter for user searches

### ISSUE THREAD

**Issue by janvanzoggel** [shijl0925/python-sonarqube-api#54]
I was experimenting with the Sonarcloud API and the Python-Sonarqube-API project and noticed that while I am able to filter all users in the API request to Sonarcloud:

https://sonarcloud.io/api/organizations/search_members?organization=XXXXXX&ps=100' 

The library function search_users returns me all users known within Sonarcloud and does not allow for a org filter:
```
sonarconn = SonarCloudClient(sonarcloud_url="https://sonarcloud.io", token="XXXXXX")
users = list(sonarconn.users.search_users()
```
and returns ALL users of sonarcloud (or at least the first paging results).

Where the function _search_groups_user_belongs_to_ does allow an organisation input:
```
   @PAGES_GET(API_USERS_GROUPS_ENDPOINT, item="groups")
    def search_groups_user_belongs_to(
        self, login, organization, q=None, selected="selected"
    ):
        """
        Lists the groups a user belongs to.

        :param login:
        :param organization: organization key.
        :param q: Limit search to group names that contain the supplied string.
        :param selected: Depending on the value, show only selected items (selected=selected), deselected items
          (selected=deselected), or all items with their selection status (selected=all).Possible values are for:
            * all
            * deselected
            * selected
          default value is selected.
        :return:
        """
```

**Comment by janvanzoggel** [comment]
Due to the sonarcloud setup of Members (and Owners) group I seem to be able to workaround this with the function:

```
users = list(sonarconn.user_groups.search_users_belong_to_group(name="Members",organization="XXXX"))`
```

**Comment by shijl0925** [comment]
This issue has been solved?

**Comment by janvanzoggel** [comment]
Yes it has. Thanks for your effort, have been using the project and all works nicely :)
