### ISSUE TITLE
How can I extract the severity data only for vulnerability in the issues field?

### ISSUE THREAD

**Issue by aleixvilaseca** [shijl0925/python-sonarqube-api#66]
Hello,
I’m trying to extract the severity data reported for the vulnerability but I’m having it extremely difficult. I’m using the python-api and when it returns the blocking and critical severities, it returns the total (the sum of bugs, vulnerabilities and code smells). Is there a way to disaggregate this information.
Can anyone help me to know if it is possible to separate this data?
Thanx

**Comment by vinod827** [comment]
Can you let me know which API you are referring to here which returns the total? And what is your expected format here?

**Comment by aleixvilaseca** [comment]
Hello @vinod827,

I'm calling the api as follows and I extract it in a json file:

issues = list(sonar.issues-search_issues(issue_type='VULNERABILITY', severity='CRITICAL, BLOCKER'))

this call does not return the specified issues, but instead dumps all data by type and severity. I just want to extract for each project that exists in sonarqube, the blocking and critical vulnerability flaws.

Using the measures_search call, it returns this result, but what it does is return the total number of blocking and critical vulnerabilities, bugs, and code_smells, while what I want to output is this same result for vulnerability only.

Thanx

**Comment by shijl0925** [comment]
update pageage to version 1.3.6

search_issues fuction support obtain specified  issues by page, not all data.
