### ISSUE TITLE
Is there a way of iterate through the repo's folders and retrieve its metrics?

### ISSUE THREAD

**Issue by JohnQ00** [shijl0925/python-sonarqube-api#69]
Hello.

I was looking for a way to get the metrics from the repo, but also from a specific folder inside the repo. The "Code" window present the folders and the files of the project, can we access it like we access the full repo? Returning metrics for a specific folder, for example?

I know your API can look into a file,

`duplications = sonar.duplications.get_duplications(key="my_project:/src/foo/Bar.php")`

But can we do this?

`sonar.measures.get_component_with_specified_measures(component: "my_project:/src/foo/")`

Thank you for your attention.

**Comment by shijl0925** [comment]
update package to version 1.3.6
demo code:
`
component = "my_project:/src/foo/"
metricKeys = "ncloc,bugs,vulnerabilities,code_smells,security_hotspots,coverage,duplicated_lines_density"
result = sonar.measure.get_component_tree_with_specified_measures(component=component,metricKeys=metricKeys, p=1, ps=100)
measures = result.get("measures")
`
