### ISSUE TITLE
sonar.projects.search_projects() returning unexpected results in version 1.3.6

### ISSUE THREAD

**Issue by JamesGormanRigUp** [shijl0925/python-sonarqube-api#70]
After upgrading from 1.3.5 to 1.3.6, searching for projects in sonarcloud by organization is no longer returning the expected results.

This is an example line of code
```
sonar.projects.search_projects(organization="org")
```

The expected return is a list of project objects that you can then iterate through, this is the behavior still seen with version 1.3.5

Instead when using 1.3.6 the returned value ends up being an array of strings: `['paging', 'components']`

In order to resolve this in the meantime, I am targeting version 1.3.5 explicitly

**Comment by autotaker** [comment]
I’m also confused by the breaking changes in 1.3.6.
A number of api returns a page instead of an iterator….

I wish to increment the major version for such changes!

**Comment by matthias-reiff** [comment]
Same for me. Please update docs accordingly.

**Comment by shijl0925** [comment]
WATCH OUT!!!
1.3.5 ```sonar.projects.search_projects``` return an iterator. But 1.3.6 return response with "paging" and "components".

```
sonar.components.search_components
sonar.favorites.search_favorites
sonar.issues.search_issues
sonar.measures.search_measures_history
sonar.measures.get_component_tree_with_specified_measures
sonar.metrics.search_metrics
sonar.project_analyses.search_project_analyses_and_events
sonar.projects.search_projects
sonar.qualitygates.get_qualitygate_projects
sonar.qualityprofiles.get_history_of_changes_on_quality_profile
sonar.qualityprofiles.get_projects_associate_with_quality_profile
sonar.rules.search_rules
sonar.user_groups.search_user_groups
sonar.user_groups.search_users_belong_to_group
sonar.webhooks.get_webhook_deliveries
```
these functions have the same situation.

return response for example:
```
{
  "paging": {
    "pageIndex": 1,
    "pageSize": 100,
    "total": 2
  },
  "components": [
    {
      "key": "project-key-1",
      "name": "Project Name 1",
      "qualifier": "TRK",
      "visibility": "public",
      "lastAnalysisDate": "2017-03-01T11:39:03+0300",
      "revision": "cfb82f55c6ef32e61828c4cb3db2da12795fd767"
    },
    {
      "key": "project-key-2",
      "name": "Project Name 1",
      "qualifier": "TRK",
      "visibility": "private",
      "lastAnalysisDate": "2017-03-02T15:21:47+0300",
      "revision": "7be96a94ac0c95a61ee6ee0ef9c6f808d386a355"
    }
  ]
}
```
