### ISSUE TITLE
API breaking changes in 1.3.6

### ISSUE THREAD

**Issue by jrjsmrtn** [shijl0925/python-sonarqube-api#74]
I spent two days debugging an issue with the `sonarqube` package. Even after digging into the docs and open issues, I had to write tests against all versions since 1.3.0 to find out that 1.3.6 was breaking results format.

The only explanation is in this _closed_ issue: https://github.com/shijl0925/python-sonarqube-api/issues/70#issuecomment-1401323551

Is it possible:

1. to mention this API breaking change in a more prominent way, in the docs, in the changelogs or on the GitHub page;
2. to bump the minor version number if the API has breaking changes in the future ?

**Comment by jrjsmrtn** [comment]
Also: could it be possible to add a `sonarqube.__version__` constant to detect the version of the package at runtime ?

**Comment by shijl0925** [comment]
Done

**Comment by tanaya-patil** [comment]
I am new to this python package. Existing tools deployed used version 1.3.0. And hence with 2.x.y many functionalities are breaking . 

Can anyone guide me to where can i find the version 1.3.0? Thank you in advance!
