### ISSUE TITLE
How to get git commit hash and date related to a sonarqube issue

### ISSUE THREAD

**Issue by Latifaa17** [shijl0925/python-sonarqube-api#77]
is there a way to get  the git commit hash and date related to a sonarqube issue?

**Comment by shijl0925** [comment]
example code:
`
    issue = client.issues.get("AYPE7CZ9rKHsJaGcj7Lk")
    component = issue.get("component")
    line = issue.get("line")

    scm = client.sources.get_source_file_scm(key=component, from_line=line, to_line=line+1)
`

commit hash and date in the scm result.
