### ISSUE TITLE
Error in request. Possibly Not Found error [404]: Component 'XXXX' on branch 'master' not found

### ISSUE THREAD

**Issue by xuri422** [shijl0925/python-sonarqube-api#78]
def get_sonarqube_info(self, branch="master", component=None, url=None, username=None, password=None):
        try:
            sonar = SonarQubeClient(sonarqube_url=url)
            sonar.auth.authenticate_user(login=username, password=password)
            _component_data = sonar.measures.get_component_with_specified_measures(
                component=component,
                branch=branch,
                metricKeys=METRICKEYS_
            )
        ........

In this code lien, have a except as:
Error in request. Possibly Not Found error [404]: Component 'XXXX' on branch 'master' not found

but in another project ,this code can run normally. the XXXX project is the first scan. In sonarquebe server, [MEASURES]-->[new code ] show result as: 
Measures on New Code will appear after the second analysis of this branch.

So, how can I revole it?

**Comment by shijl0925** [comment]
I tested my project, which is scanned for the first time, I didn't find the problem you described.

**Comment by xuri422** [comment]
Error in request. Possibly Not Found error [404]: Component 'XXXXX' on branch 'master' not found
Traceback (most recent call last):
  File "G:\PycharmProjects\test1\AutoCodeScan.py", line 609, in execute_scan
    SonarqubeManager().main(project_name, project_ver, emailaddr)
  File "G:\PycharmProjects\test1\sendmail.py", line 411, in main
    sonarqube_data = self.get_sonarqube_info(branch=SonarqubeConfig["branch"],
  File "G:\PycharmProjects\test1\sendmail.py", line 225, in get_sonarqube_info
    component_data = sonar.measures.get_component_with_specified_measures(
  File "C:\Python3\lib\site-packages\sonarqube\utils\common.py", line 132, in inner_func
    response = self._get(url_pattern, params=params)
  File "C:\Python3\lib\site-packages\sonarqube\utils\rest_client.py", line 141, in _get
    return self.request("GET", path=path, params=params, data=data, headers=headers)
  File "C:\Python3\lib\site-packages\sonarqube\utils\rest_client.py", line 99, in request
    raise NotFoundError(msg)
sonarqube.utils.exceptions.NotFoundError: Error in request. Possibly Not Found error [404]: Component 'XXXXXX' on branch 'master' not found

This is the error message. I found it in many project scanned.
