### ISSUE TITLE
1.2.x Versions not available anymore on pypi

### ISSUE THREAD

**Issue by petermbauer** [shijl0925/python-sonarqube-api#79]
Hi,
I was using Version 1.2.5 so far from PyPi and found today that no 1.2.x Versions are available anymore. Also no releases or tags in this repo.
What happened or what have i missed?

**Comment by nzdjb** [comment]
Likewise 1.3.x.

**Comment by shijl0925** [comment]
python-sonarqube-api no longer support whole web api functions,but you can found them in python-sonarqube-api(professional edition) .

**Comment by petermbauer** [comment]
@shijl0925 it is of course your right to change the licensing to make some profit, but removing older versions and braking stuff on the side of your potential new customers is not a nice move.

Will the other 1.x versions also be removed?

**Comment by shijl0925** [comment]
Why do I need to pay for this library? The Sonarqube web API has a lot of interfaces and complex parameters. I spend a lot of free time maintaining it. In order to improve code quality and continuous maintenance, the professional version requires payment. I will transfer some money to invest more effort in maintaining it.

**Comment by shijl0925** [comment]
@petermbauer  I keep these libraries before I removed them, If you want it, send email to me. You can find my gmail on my profile.

**Comment by stojan-jovic** [comment]
It's absolutely fine to make some money for your hard work, but it's not fine to break everything overnight for library users by removing previously free resources (AGPLv3 I think) without any previous notice (my apologies if that happened but we missed it). Very unprofessional in my opinion!

**Comment by vittoriocanilli** [comment]
@shijl0925 could you please highlight in the documentation which functions are only available in the professional edition? 

For instance on the documentation page for [projects](https://python-sonarqube-pro-api.readthedocs.io/en/latest/examples/projects.html), you could point out that the `search_projects` is available on all editions, while the `create_project` function can only be used on the professional edition. Thanks in advance.

**Comment by shijl0925** [comment]
@vittoriocanilli  Professional Edition's extra features have been remarked by using "Only available on the professional edition" in API Document. "Available on all editions" mean you can use these function on all editions.
see detail: https://python-sonarqube-pro-api.readthedocs.io/en/latest/sonarqube.rest.html#submodules

**Comment by shijl0925** [comment]
@vittoriocanilli  Professional Edition's extra features have been remarked by using "Only available on the professional edition" in API Document. "Available on all editions" mean you can use these function on all editions.
see detail: https://python-sonarqube-pro-api.readthedocs.io/en/latest/sonarqube.rest.html#submodules

**Comment by shijl0925** [comment]
the other 1.x versions will be removed In the coming week.

**Comment by jellonek** [comment]
@petermbauer @nzdjb https://github.com/gjabouley-invn/python-sonarqube-api recent fork with all previous history. unfortunately without other branches or tags...

rewriting the history with removal of info about all contributions is a really unprofessional move and most probably is violating rights (given them by AGPL - hint: attribution) of all 18 contributors.

@shijl0925 i hope that you will reconsider from legal perspective (please read once again the license which you just changed) this history rewrite (previously used by you license allows you to do that, but AGPL which you have chosen recently does have a point about attribution and you have in this repo at least 18 listed contributors - so you are not the only author in this repo, while you are the main maintainer/repo owner).

**Comment by jellonek** [comment]
@stojan-jovic Jialiang was using previously on this repo MIT license so removal of releases was perfectly fine with it.
even AGPL which is set there currently has nothing to do about these releases removal - only history rewriting seems legally uncertain from AGPL perspective.

**Comment by jellonek** [comment]
@petermbauer @nzdjb if you need tags for 1.2.x-1.3.0 - check this fork: https://github.com/kravvcu/python-sonarqube-api/tags

**Comment by Hany-Benz** [comment]
this is really unprofessional, changing license overnight and remove all the previous versions artifacts under AGPL is very bad

**Comment by nzdjb** [comment]
> @petermbauer @nzdjb if you need tags for 1.2.x-1.3.0 - check this fork: https://github.com/kravvcu/python-sonarqube-api/tags

Thanks. I implemented the functionality I needed myself instead and no longer use this library.

**Comment by Malgosiatobiasz1** [comment]
Hi @shijl0925 , I would like to ask about the use of the pro version, this is the cost of $5 plus vat, what is the period of time for this money and does it entitle the buyer to use all new versions that will be created?

**Comment by shijl0925** [comment]
> Hi @shijl0925 , I would like to ask about the use of the pro version, this is the cost of $5 plus vat, what is the period of time for this money and does it entitle the buyer to use all new versions that will be created?

@Malgosiatobiasz1  Payment only needs to be made once, and updates will be provided for free. (send by email or download updates from the gumroad website)

**Comment by Malgosiatobiasz1** [comment]
> > Hi @shijl0925 , I would like to ask about the use of the pro version, this is the cost of $5 plus vat, what is the period of time for this money and does it entitle the buyer to use all new versions that will be created?
> 
> @Malgosiatobiasz1 Payment only needs to be made once, and updates will be provided for free. (send by email or download updates from the gumroad website)

one payment = lifetime license?

**Comment by shijl0925** [comment]
@Malgosiatobiasz1 one payment = lifetime license, and continuous updates.

**Comment by petermbauer** [comment]
> the other 1.x versions will be removed In the coming week.

looks like you already removed them. seriously, wtf?

**Comment by candrews** [comment]
In business, reputation is everything.

There, when someone wants to monetize a project, starting with a foundation of goodwill is a good and common strategy.

For years, the `python-sonarqube-api` has been a trustworthy, reliable, well-maintained library. It had a good brand and many happy users.

When the maintainer wanted to transition to a freemium, he could have leveraged that positive reputation and the established user base by saying, "all new features will only be added to the pro version" or "development of this free version has ceased; pay for and use the pro version to received continued bug fixes and new features." I suspect users would have been okay with that, and some would have happily paid for the pro version.

However, instead, the maintainer deleted the existing versions, breaking the projects of all existing users. As a user, I'm really unhappy - I had to waste hours of my effort to address this unnecessary crisis, and my users are also really unhappy. Now, neither my management nor my users like `python-sonarqube-api` - none of us will trust this project or its maintainer again.

What positive reputation this project had is now irreparably tarnished, and along with it, I suspect all hopes for the monetization so desperately desired have likewise suffered the same fate.

**Comment by candrews** [comment]
I strongly believe that pypi should not allow projects to delete releases to prevent this kind of malicious, extortionous attack from impacting anyone else in the future. I encourage other to raise this issue with pypi; I've added my voice at https://discuss.python.org/t/stop-allowing-deleting-things-from-pypi/17227/108

**Comment by Rosuav** [comment]
Came here from the PyPI discussion thread on Discourse, and I'm confused by something: if this code is released under the AGPL, doesn't that mean anyone can just grab the source code and rerelease it without the payment requirement? And if only the free version is AGPL, with the premium version under a different license, you'd have to prove that the premium version isn't a derivative work of the free version.

In any case, I agree with @candrews that causing problems for *people not even connected to the project* is a pretty effective way to destroy your reputation - there are people on the Python Discourse whose first experience of your project is a dirty business practice and possible license violation. Not something that encourages purchases.
