### ISSUE TITLE
AttributeError: 'SonarQubeProjects' object has no attribute 'create_project' with the latest version(2.0.3)

### ISSUE THREAD

**Issue by sridhar-parvathala** [shijl0925/python-sonarqube-api#81]
we were using version 2.0.0 and create_project function was available . Version 2.0.0 no longer exists, so we tried to use latest version ( 2.0.2 and 2.0.3 ). However create_project doesn't exist in the latest version.

How do we create the project with the using the latest api ?

**Comment by shijl0925** [comment]
You can find the sonar.projects.create_project in the Professional Edition package. (Only available on the professional edition)
see detail:
https://python-sonarqube-pro-api.readthedocs.io/en/latest/sonarqube.rest.html#sonarqube.rest.projects.SonarQubeProjects.create_project
