### ISSUE TITLE
New version Sdk missed so many useful method could rollback or merge old method to current version?

### ISSUE THREAD

**Issue by Dennis981210** [shijl0925/python-sonarqube-api#82]
New version Sdk missed so many useful method could rollback or merge old method to current version?
For Example in Version 1.3.6 I can use qualitygates.get_project_qualitygates_status to get project qualitygates status but now there is no existing method for that api...
![image](https://github.com/shijl0925/python-sonarqube-api/assets/46859274/553768dc-6063-4c79-8d3c-17f8a9f1a756)

**Comment by shijl0925** [comment]
The missing methods can be found in the professional edition.

https://github.com/shijl0925/python-sonarqube-api#editions

**Comment by Dennis981210** [comment]
> The missing methods can be found in the professional edition.
> 
> https://github.com/shijl0925/python-sonarqube-api#editions

Is there any other way pay for the professional version SDK? Chinese Visa Card pay on gumroad.com Website  can not successed... Is there any other way to pay ?like wechat or 支付宝

**Comment by shijl0925** [comment]
@Dennis981210  You can find my Alipay image(支付宝) here and add a note to your email address(备注邮箱地址). I will send the software to you via email.

https://github.com/shijl0925/python-sonarqube-api/blob/master/docs/alipay.jpg

**Comment by enes-alatas** [comment]
Dear @shijl0925

I really appreciate the effort that you put into developing and maintaining this project. And of course, I completely understand that you want to make some money out of it. But you can not just force people to pay for the features that are originally created under the MIT license by rewriting (i.e. rebasing) the repo's history and removing the previous releases from both the PyPI index and GH. Apart from the ethical side, you can not even do that legally. Open-source projects, especially the ones with the MIT license, do not work like this. You, naturally, can change the license of newer releases and ask for whatever you like for these new versions but the older version shall remain under their original licenses.

In this sense, I just forked one of the old ones and will use it for the older releases. Just for your information.

Cheers.

**Comment by juliantrzeciak** [comment]
@enes-alatas Can you please share the old ones? (I'm deep in an unpleasant place.. ) Thanks in advance
