### ISSUE TITLE
API breaking changes on 2.x not documented + previous packages wiped from everywhere

### ISSUE THREAD

**Issue by xmsanchez** [shijl0925/python-sonarqube-api#84]
I know this has similarities with [this issue](https://github.com/shijl0925/python-sonarqube-api/issues/74) but I believe this is a more serious problem.

I do not really understand how it is possible that **previous releases** has been **completely removed** from everywhere and all the **breaking changes** are **not mentioned** anywhere. These changes broke functionality in a complex tool that we were close to put to production and the team is not confident anymore to use this library.

It's not my intention to blame no one, I just want to note that this is a problem that should be prevented.

In my opinion:
- **Previous releases shouldn't be removed**, not only from pip repositories but also from the code repo (why even the previous tags has been removed?).
- If there is some kind of security issues with previous versions -which would be understandable to remove- then **it should be documented** somewhere.
- Breaking changes between versions **should be documented**, even more when there is a major release. Now it's all trial and error or just look at the latest docs (not sure if they're up-to-date, though).

If I'm just missing something, please, I kindly apologize and I'd appreciate any clarification to understand it.

Again, it's not my intention to blame somebody! I appreciate all the effort from contributors to open-source, I want that to be clear :-)

**Comment by tanaya-patil** [comment]
I was currently looking out for v1.3.0 and I completely agree with @xmsanchez . Need some light to be thrown here.

**Comment by shijl0925** [comment]
The Previous releases packages(from 1.2.3 to 1.3.7) has been remade and restored. such as:
1.3.7 , the link: https://pypi.org/project/python-sonarqube-api/1.3.7.post0/

**Comment by xmsanchez** [comment]
Great! Thanks a lot. By the way, what is the reason why the permissions class has disappeared in 2.x?

```
AttributeError: 'SonarEnterpriseClient' object has no attribute 'permissions'
```

This is one of the stoppers I have with the new version. Since there is no changelog describing the breaking changes I'm not sure if there's an alternative or not. I quickly searched the source code but I couldn't find it.

**Comment by shijl0925** [comment]
> 

you can find the permissions class in these packages low than 2.x.
