### ISSUE TITLE
sonar.components is not found/supported

### ISSUE THREAD

**Issue by ampz9** [shijl0925/python-sonarqube-api#86]
hello,

Was following this example: https://python-sonarqube-api.readthedocs.io/en/latest/sonarqube.rest.html#module-sonarqube.rest.components and the components module is no longer supported.

```
Traceback (most recent call last):
  File "sonar.py", line 4, in <module>
    components_tree = sonar.components.get_components_tree(component="component_key")
AttributeError: 'SonarQubeClient' object has no attribute 'components'
```
Is this expected?

thanks!

**Comment by shijl0925** [comment]
the components module Only available on the professional edition

**Comment by ampz9** [comment]
Thanks, just noticed https://python-sonarqube-api.readthedocs.io/en/latest/#editions

Will review closely
