### ISSUE TITLE
AttributeError: 'SonarEnterpriseClient' object has no attribute 'permissions'

### ISSUE THREAD

**Issue by leofin** [shijl0925/python-sonarqube-api#87]
Hello,

I'm facing an issue that the function permissions don't exist anymore. Can anyone help me?

>>> import os
>>> import yaml
>>> import re
>>> from sonarqube import SonarEnterpriseClient
>>> from sonarqube.utils.exceptions import ValidationError, NotFoundError
>>> 
>>> URL = "https://sonar.example.com"
>>> USERNAME = os.environ.get('USERNAME', 'admin')
>>> PASSWORD = os.environ.get('PASSWORD')
>>> PAGESIZE = 10
>>> 
>>> sonar = SonarEnterpriseClient(sonarqube_url=URL, username=USERNAME, password=PASSWORD)
>>> sonar.permissions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'SonarEnterpriseClient' object has no attribute 'permissions'

Version 1.3.6 was working.

I checked the code, and it looks like the permissions class is missing.

**Comment by shijl0925** [comment]
https://github.com/shijl0925/python-sonarqube-api#editions

**Comment by leofin** [comment]
Thank you for the fast answer.
