### ISSUE TITLE
'SonarQubeClient' object has no attribute 'settings'

### ISSUE THREAD

**Issue by dvelardez** [shijl0925/python-sonarqube-api#90]
I can no longer update the settings although the [documentation](https://python-sonarqube-api.readthedocs.io/en/latest/examples/settings.html) indicates that it is possible.
This [commit](https://github.com/shijl0925/python-sonarqube-api/commit/dbdd3d0ad2559ee7fe98af6cc338b5ad1744c928) breaks the compatibility of my app, is there a workaround to update SonarQube settings?

I am getting this error on my app: 'SonarQubeClient' object has no attribute 'settings'
Below is a part of my code:

```
def update_settings(args):
    # oidc configuration
    sonar = SonarQubeClient(sonarqube_url=args.Url, username=args.Username, password=args.Password)
    sonar.settings.update_setting_value(key='sonar.core.serverBaseURL', value=args.Url)
    sonar.settings.update_setting_value(key='sonar.auth.oidc.enabled', value='true')
    sonar.settings.update_setting_value(key='sonar.auth.oidc.issuerUri', value=args.IssuerURI)
    sonar.settings.update_setting_value(key='sonar.auth.oidc.clientId.secured', value=args.ClientID)
    sonar.settings.update_setting_value(key='sonar.auth.oidc.clientSecret.secured', value=args.ClientSecret)
    sonar.settings.update_setting_value(key='sonar.auth.oidc.groupsSync', value='true')
    sonar.settings.update_setting_value(key='sonar.auth.oidc.groupsSync.claimName', value=args.GroupsClaimName)
```

I appreciate if you can help me.

**Comment by shijl0925** [comment]
Only available on the professional edition
https://python-sonarqube-pro-api.readthedocs.io/en/latest/examples/settings.html
