### ISSUE TITLE
Missing search_measures_history from lib

### ISSUE THREAD

**Issue by iDevoid** [shijl0925/python-sonarqube-api#98]
# error
<img width="862" alt="Screenshot 2024-03-22 at 5 40 53" src="https://github.com/shijl0925/python-sonarqube-api/assets/47969743/fd73d3e5-75ea-4dfd-82f5-f6bb91ee85a7">

# documentation
the function exists on documentation: 
https://python-sonarqube-api.readthedocs.io/en/latest/examples/measures.html

## referring to file
I cannot find it on the following file too
https://github.com/shijl0925/python-sonarqube-api/blob/248b0d543a821689fbbb0765effb310910448145/sonarqube/rest/measures.py#L11

**Comment by shijl0925** [comment]
Only available on the professional edition.
https://python-sonarqube-pro-api.readthedocs.io/en/latest/examples/measures.html
